select distinct division_order_id
      ,division_id
      ,payment_processor_name
      ,payment_method_id
    --  ,payment_amount
      ,transaction_currency
      ,(case 
       when payment_method_id = 'AmericanExpress' and response_message in (' FR5',' S01') then 'AmEx Case Update'
       when (select max(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed' and payment_amount between .95*rpt.payment_amount and 1.05*rpt.payment_amount) - (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed' and payment_amount between .95*rpt.payment_amount and 1.05*rpt.payment_amount) > 0 then '2nd Time CB'
       when (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status in ('Submitting', 'Requested','Completed')) - (select max(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') < 0 then 'Refund Pre-CB'
       when (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') = rpt.payment_amount and (select count(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') > 1 then 'High CB Combined Splits'
       when rpt.payment_amount <> (select payment_amount from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and rownum < 2) and (select payment_amount from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and rownum < 2) between .95*rpt.payment_amount and 1.05*rpt.payment_amount then 'Currency Diff'
       when (select max(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and payment_method_id = 'AmericanExpress') <> rpt.payment_amount and (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed' and payment_method_id = 'AmericanExpress') <> (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and payment_method_id = 'AmericanExpress') then 'AmEx Issue'
       when (select min(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and payment_method_id = 'AmericanExpress') <> rpt.payment_amount and (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed' and payment_method_id = 'AmericanExpress') <> (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and payment_method_id = 'AmericanExpress')  then 'AmEx Issue'
       when (select count(cpg_transaction_id) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed' and payment_method_id = 'AmericanExpress') > 1 then 'AmEx Multi-CB'
       when (select count(cpg_transaction_id) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') > 1 and (select min(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') <> (select min(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') then 'No CB on Lower Split'
       when (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Completed') is not null and (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Completed') between rpt.creation_date - 2 and rpt.creation_date + 2 then 'Refund within 2 days of CB'
       when (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Declined') is not null then 'Declined Refund'
       when (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Cancelled') is not null then 'Cancelled Refund'
       when (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Failed') is not null then 'Failed Refund'
       when (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Completed') is not null then 'Refund'
       when (select max(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') - (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') <> 0 and (select status from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBackRevrs' and status = 'Completed' and rownum < 2) is null and response_code <> '80' then 'Split on dif Day'
       when rpt.payment_amount <> (select payment_amount from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed' and rownum < 2) and (select count(cpg_transaction_id) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') < 2 then 'Sale and CB Amount do not match' 
       when (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Failed') is not null and (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Failed') between rpt.creation_date - 2 and rpt.creation_date + 2 then 'Failed Refund' 
       when (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Failed') is not null and (select min(creation_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Refund' and status = 'Failed') < rpt.creation_date  then 'Failed Refund Pre CB' 
       when (select 2*sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') = (select sum(payment_amount) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') and (select 2*count(cpg_transaction_id) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'Settle' and status = 'Completed') = (select count(cpg_transaction_id) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') then 'Double CB'
       when payment_method_id = 'DirectDebit' then 'DD Fraud Return/Detection'
       when response_code = '80' and payment_method_id = 'Visa' then 'Visa 80'
       when (select max(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') = (select min(settlement_date) from rcn_payment_transaction where division_order_id = rpt.division_order_id and transaction_type = 'ChargeBack' and status = 'Completed') then '1st Time CB'
       else 'Other' end)CB_Result

from rcn_payment_transaction rpt

where division_order_id in 
and settlement_date between '7/1/2019' and sysdate
and creation_date > sysdate - 40
and transaction_type = 'ChargeBack'
and status = 'Completed'
--and division_order_id = '11202711400'
--and settlement_date between '01-jan-13' and '31-jan-13'
