SELECT RLI.REQUISITION_ID
, CPD.DISPLAY_NAME
, TO_CHAR(REGEXP_SUBSTR(NNC.MESSAGE, '[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}',1,rownum)) AS ProdData

FROM REQ_LINE_ITEM RLI 

JOIN NTF_NOTIFICATION NN ON NN.REQUISITION_ID = RLI.REQUISITION_ID AND NN.EVENT_NAME = 'User Order Confirmation event'
JOIN NTF_NOTIFICATION_CONTENT NNC ON NN.NOTIFICATION_ID = NNC.NOTIFICATION_ID
LEFT OUTER JOIN CAT_PRODUCT_DATA CPD ON RLI.PRODUCT_DATA_ID = CPD.PRODUCT_DATA_ID


WHERE RLI.REQUISITION_ID IN ('11630545372')
