--Needs to be run against a CFS DB like CFSPRD04.  Will not run on Equator.
SELECT oa.platform                                          AS "Platform",
  oa.order_id                                               AS "Order ID",
  oa.usd_order_total                                        AS "Order Amt USD",
  oa.affiliate_id                                           AS "Affiliate ID",
  it.vendor_id                                              AS "Vendor ID",
  TRUNC(oa.platform_order_date)                             AS "Order Date",
  TRUNC(cb.chargeback_date)                                 AS "CB Date",
  TRUNC(cb.chargeback_date) - TRUNC(oa.platform_order_date) AS "Order-CB Delta",
  cb.reason_code                                            AS "CB Reason Code",
  DECODE(cb.reason_code, '4540' , 'Fraud', '63' , 'Fraud', '37' , 'Fraud', '0' , 'Non-Fraud.No.Other.Info.Provided', '30' , 'Services.Not.Provided.or.Merchandise.Not.Received', '41' , 'Cancelled.Recurring.Transaction', '53' , 'Not.as.Described.or.Defective.Merchandise', '57' , 'Fraudulent.Multiple.Transactions', '60' , 'Requested.Copy.Illegible', '62' , 'Counterfeit.Transaction', '70' , 'Account.Number.on.Exception.File', '71' , 'Declined.Authorization', '72' , 'No.Authorization.Obtained', '73' , 'Expired.Card', '74' , 'Late.Presentment', '75' , 'Cardholder.Does.Not.Recognize.the.Transaction', '76' , 'Incorrect.Transaction.Code', '77' , 'Non.Matching.Acct.Number', '78' , 'Service.Code.Violation', '79' , 'Requested.Transaction.Information.Not.Received', '80' , 'Incorrect.Transaction.Amount.or.Acct.Number', '81' , 'Fraudulent.Transaction.-.Card.Present', '82' , 'Duplicate.Processing', '83' , 'Fraudulent.Transaction.-.Card.Not.Present', '85' , 'Credit.Not.Processed', '86' ,
  'Paid.by.Other.Means', '90' , 'Services.Not.Rendered.-.ATM.or.VisaTravel.Money.Transactions', '93' , 'Risk.Identification.Service.(RIS)', '96' , 'Transaction.Exceeds.Floor.Limit', '28' , 'Cardholder.Requests.Copy.Bearing.Signature', '29' , 'Request.for.T&E.Documents', '30' , 'Cardholder.Dispute.-.Cardholder.Requests.Draft', '33' , 'Legal.Process.or.Fraud.Analysis', '34' , 'Repeat.Request.for.Copy', '4801' , 'Requested.Transaction.Information.not.Received', '4802' , 'Requested/Required.Information.Illegible.or.Missing', '4803' , 'Documentation.Received.Invalid/Incomplete', '4804' , 'Duplicate.Processing', '4807' , 'Warning.Bulletin.Filed', '4808' , 'Requested/Required.Authorization.Not.Obtained', '4812' , 'Account.Number.Not.on.File', '4831' , 'Transaction.Amount.Differs.(Authorization.to.Settlement)', '4834' , 'Duplicate.Processing', '4835' , 'Card.Not.Valid.or.Expired', '4837' , 'No.Cardholder.Authorization', '4840' , 'Fraudulent.Processing.of.Transaction', '4841' ,
  'Cancelled.Recurring.Transaction', '4842' , 'Late.Presentment', '4846' , 'Correct.Transaction.Currency.Code.Not.Provided', '4847' , 'Exceeds.Floor.Limit.-.Not.Authorized.and.Fraudulent.Transaction', '4849' , 'Questionable.Merchant.Activity', '4850' , 'Credit.Posted.as.a.Purchase', '4853' , 'Merchandise/Services.Not.as.Described', '4854' , 'Cardholder.Dispute.Not.Elsewhere.Classified.(US.Only)', '4855' , 'Non-receipt.of.Merchandise', '4856' , 'Defective.Merchandise', '4857' , 'Card.Activated.Telephone.Transaction', '4859' , 'Services.Not.Rendered', '4860' , 'Credit.Not.Processed', '4862' , 'Counterfeit.Transaction.Magnetic.Stripe.POS.Fraud', '4863' , 'Cardholder.Does.Not.Recognize.-.Potential.Fraud.(US.Only)', '4870' , 'Chip.Liability.Shift', '4871' , 'Chip.&.PIN.Liability.Shift', '4905' , 'Invalid.Acquirer.Reference.Data.on.Second.Presentment', 'AL' , 'Cardholder.challenges.the.validity.of.an.airline.Card.Sale', 'AP' , 'Automatic.Payment.Dispute', 'AW' , 'Altered.Amount.Dispute',
  'CA' , 'Cash.Advance.Dispute.other.than.Discover.Network.ATM.Transaction', 'CD' , 'Credit.Posted.as.Card.Sale', 'CR' , 'Cancelled.Reservation', 'DA' , 'Merchant.Received.Declined.Authorization.Response', 'DP' , 'Duplicate.Processing', 'EX' , 'Expired.Card', 'IC' , 'Illegible.or.Missing.Transaction.Documentation', 'IN' , 'Invalid.Card.Number', 'IS' , 'Documentation.in.response.to.Retrieval.Request.Missing.Valid/Legible.Signature', 'LP' , 'Late.Presentment', 'NA' , 'Merchant.Did.Not.Obtain.Positive.Authorization.Response', 'NC' , 'Not.Classified.-.Cardholder.challenges.sale.and.no.other.Reason.Code.applies', 'RG' , 'Non-receipts.of.Goods.or.Services', 'RM' , 'Quality.of.Goods.or.Services.Dispute', 'RN1' , 'Additional.Credit.Requested', 'RN2' , 'Credit.Not.Received', 'SV' , 'Prepaid/Gift.card.Transaction.Dispute', 'TF' , 'Violation.of.Operating.Regulations', 'UA01' , 'No.Authorization.Request.from.Merchant', 'UA02' , 'Issuer.Provided.Declined.Authorization', 'UA03' ,
  'Amount.Billed.Exceeds.amount.Authorized.by.Issuer', 'UA11' , 'Swiped.Card.Transaction.-.No.Signature.Obtained', 'UA12' , 'Swiped.Card.Transaction.-.Invalid.Signature', 'UA18' , 'Swiped.Card.Transaction.-.Illegible.Copy.of.Receipt', 'UA21' , 'Keyed.Card.Transaction.-.No.Signature.Obtained', 'UA22' , 'Keyed.Card.Transaction.-.Invalid.Signature', 'UA23' , 'Keyed.Card.Transaction.-.Invalid.Card.Imprint', 'UA28' , 'Keyed.Card.Transaction.-.Illegible.Copy.of.Transaction.Documentation', 'UA31' , 'CNP.Transaction.-.Invalid.Proof.of.Delivery', 'UA32' , 'CNP.Transaction.-.Merchant.did.not.perform.AVS.or.CID.check', 'UA38' , 'CNP.Transaction.-.Illegible.Copy.of.Transaction.Documentation', 'UA99' , 'Non-Compliance.with.Operating.Regulations', 'A01' , 'Amount.Differs.from.Authorization.to.Settlement', 'A02' , 'Did.Not.Receive.Valid.Authorization.Approval', 'A03' , 'Valid.6.digit.Authorization.code.Not.Provided', 'A04' ,
  'Valid.Authorization.Not.Obtained.–.You.were.advised.to.call.AmEx.directly', 'A05' , 'Authorization.Approval.Code.Not.on.Record', 'A06' , 'Overlimit.Authorization.Approval.Not.Obtained', 'A07' , 'Authorization.Was.Declined', 'A08' , 'Charge.submitted.After.Authorization.Expired.(Valid.30.days)', 'A09' , 'Charge.submitted.After.Authorization.Expired.(Valid.30.days)', 'A10' , 'Transaction.did.not.Receive.Valid.Approval', 'C01' , 'Credit.Agreed.to.Provide.Cardholder.Not.Received', 'C02' , 'Credit.Agreed.to.Provide.Cardholder.Not.Received', 'C03' , 'Credit.Agreed.to.Provide.Cardholder.Not.Received', 'C04' , 'Cardholder.Provided.Proof.Merchandise.Returned', 'C05' , 'Cardholder.Provided.Proof.Order.Cancelled', 'C06' , 'Credit.Not.Processed', 'C07' , 'Disputes.Return.Policy', 'C08' , 'Merchandise.Not.Received', 'C09' , 'Services.Not.Rendered', 'C10' , 'Discontinue.Recurring.Billing.–.Second.Contact/Notice', 'C11' , 'Cardholder.Claims.Charge.Greater.than.what.they.Signed.for', 'C12' ,
  'Cardholder.Claims.Charge.Greater.than.what.they.Signed.for', 'C13' , 'Cardholder.Paid.by.Other.Means', 'C14' , 'Cardholder.Provided.Proof.Paid.by.Other.Means', 'C15' , 'Cardholder.Provided.Proof.Paid.by.Other.Means', 'C16' , 'International.Card.-.Cant.Charge.for.this.good.or.service', 'C17' , 'AmEx.Card.Not.Valid.In.US', 'C18' , 'Reservation.Cancelled.-.Credit.Due', 'C19' , 'Double.Billing.–.Charged.for.No.Show.and.Reservation', 'C25' , 'Cardholder.received.Merchandise.', 'C26' , 'Discontinue.all.Future.Billings.to.this.Account', 'C27' , 'Cardholder.No.Longer.Disputes.Charges.(Positive.Signal)', 'C28' , 'Charge.Submitted.After.You.Were.Advised.to.Discontinue.Future.Billing', 'C29' , 'Supporting.Documentation.Provided.by.Merchant.shows.Overcharge', 'F01' , 'Did.Not.Receive.Valid.Authorization.Approval.for.Amount.of.Charge', 'F05' , 'No.Signature', 'F06' , 'Client.information.does.not.match.Cardholder.info', 'F08' , 'Unable.to.Support.“Signature.on.File”.charge', 'F10' ,
  'Did.not.receive.Full.Mag.Stripe.Data', 'F11' , 'Signature.is.not.that.of.Cardholder’s', 'F12' , 'Signature.Misspelled', 'F13' , 'Signature.differs.from.name.on.card', 'F14' , 'Cardholder.Signature.was.Not.Obtained', 'F15' , 'Self.Directed.Charged.and.Signed.Documentation.not.Available', 'F16' , 'Customer.didnt.Place.Order.-.Goods.Never.Received.-.Not.Shipped.to.Billing.Address', 'F17' , 'Tickets.Sent.to.address.other.than.Cardholder.address.and.Not.Received', 'F18' , 'Merchandise.not.shipped.Cardholder.billing.address.and.Cardholder.disputes.billing', 'F19' , 'Cardholder.Claims.Merchandise.Not.Received.and.was.not.sent.to.Billing.Address', 'F20' , 'Expired.Card', 'F21' , 'Card.Not.Valid', 'F22' , 'Card.Expired.or.Not.Yet.Valid', 'F23' , 'Card.Expired.when.Ticket.was.Accepted', 'F24' , 'Multiple.Charges', 'F25' , 'Did.Not.Receive.Authorization.Approval.for.Total.Amount.Charged', 'F26' , 'Name.Provided.on.Transaction.is.Not.Cardholder.Name', 'F27' ,
  'Supporting.Documentation.Does.Not.Bear.Cardholder’s.Name', 'F28' , 'Cardholder.Claims.Fraudulent.Use.of.Cards.for.Mail.or.Electronic.Tickets.Order', 'FR1' , 'Establishment.on.Full.Recourse/Immediate.Chargeback.Program', 'FR2' , 'Establishment.on.Full.Recourse/Immediate.Chargeback.Program', 'FR3' , 'Cardholder.has.No.Knowledge.of.Charge.after.Supporting.Documents.Provided', 'FR4' , 'Establishment.on.Immediate.Chargeback.Agreement', 'FR5' , 'Establishment.on.Immediate.Chargeback.Program', 'FR6' , 'Establishment.on.Partial.Immediate.Chargeback.Agreement', 'FR40' , 'Establishment.on.Immediate.Chargeback.Agreement', 'M01' , 'Chargeback.Authorization.Received.and.Processed', 'M02' , 'Processed.Credit.Establishment.Requested', 'M05' , 'Credit.Authorized.but.Cardholder.Does.Not.Agree.to.Amount', 'M07' , 'Cannot.Bill.Cardholder.from.(Hotel).Room.Damages', 'M08' , 'Cannot.Bill.Cardholder.from.Damages', 'M09' , 'Your.Contract.with.AmEx.does.Not.permit.billing.for.Damages', 'M15' ,
  'Account.No.Longer.Active', 'M16' , 'Charge.Incurred.after.Account.was.Cancelled', 'M17' , 'Cardholder’s.Account.Cancelled.at.time.Charge.was.Incurred', 'M18' , 'Second.notice.of.Inactive.Account', 'M30' , 'Submitted.file.not.processed.because.it.appears.to.be.Duplicate', 'M32' , 'Processed.Adjustment.to.your.Account', 'M34' , 'Establishment.Not.on.CARDeposit.Program.and.you.may.Not.Bill.this.type.of.charge', 'M35' , 'Unspecified.or.Other.Adjustment.(Explanation.Included)', 'M36' , 'Unspecified.or.Other.Adjustment', 'M37' , 'Credit.must.be.processed.to.Cardholder’s.AmEx.account', 'M41' , 'Support.has.been.provided.to.Cardholder.who.still.denies.charge', 'M47' , 'Cardholder.had.no.Knowledge.of.charge', 'M48' , 'Chargeback.Reversed.(Positive.Signal)', 'P01' , 'Transaction.submitted.for.invalid/incorrect.Account.number', 'P02' , 'Transaction.submitted.for.invalid/incorrect.Account.number', 'P05' , 'Transaction.Processed.in.Wrong.Amount', 'P06' , 'Charge.Submitted.Late', 'P07' ,
  'Charge.Not.Submitted.in.Reasonable.Time.after.Charge.was.incurred', 'P08' , 'Cardholder.Claims.Same.Transaction.Posted.Twice.on.Account', 'P10' , 'AmEx.Records.Indicate.Duplicate.Billing', 'P11' , 'Cardholder.Claimed.Duplicate.Billing.and.you.did.Not.Provide.Support.for.all.Charges', 'P14' , 'Invalid.Charge', 'P15' , 'Complete.Response/Documentation.Not.Received.with.Specified.Time.Frame', 'P16' , 'Original.Response.to.Inquiry.not.Received.with.Specified.Time.Frame', 'P17' , 'Missed.Deadline.to.Supply.Documentation.for.Representment', 'P18' , 'Response.Received.but.Not.Agreed.Credits', 'P19' , 'Charge.Submitted.on.Invalid.Plastic.Number', 'P20' , 'Credit.Submitted.on.Invalid.Plastic.Number', 'P21' , 'Transaction.was.Submitted.on.a.Test.Account.Number', 'R01' , 'Full.Shipping.Information.Not.Provided.on.Proof.of.Delivery', 'R02' , 'Delivery.Address.not.Provided.as.Requested', 'R03' , 'Insufficient.Documentation.-.Itemized.Receipt', 'R04' , 'Reply.Did.Not.Address.Cardholder.Dispute'
  , 'R05' , 'Cannot.Bill.Cardholder.Account.for.Check.that.has.been.Returned', 'R06' , 'Customer.didnt.Place.Order.&.Goods.Never.Received', 'R07' , 'Delivery.Address.and.Signed.Proof.of.Delivery.Not.Provided', 'R10' , 'Supporting.Documentation.Provided.Did.Not.Include.Name.and/or.Signature', 'R13' , 'Second.Inquiry.to.Request.Information.Regarding.Charge', 'R14' , 'Response.to.Inquiry.Not.Received.within.time.frame', 'R15' , 'Documentation/Support.Agreed.to.Not.Received', 'R17' , 'Documentation/Support.Received.After.Debit.has.been.Made', 'R20' , 'Did.Not.Receive.Reply', 'R21' , 'Reply.Received.After.AmEx.charged.your.Account', 'R22' , 'Support.Received.and.Chargeback.Reversed.(Positive.Signal)', 'R23' , 'Terms.and.Conditions.and/or.Proof.of.Usage.by.Cardholder.Not.Provided', 'S01' , 'Request.for.Chargeback.Reversal.Reviewed.and.Denied.–.Account.Not.Credited', 'T01' , 'Issuer.Provides.Proof.Tickets.were.Returned.and.Cardholder.did.not.Receive.Credit', 'T02' ,
  'Tickets.were.voided.and.Cardholder.Credit.Not.Received', 'T03' , 'Tickets.are.mirror.images.tickets', 'T04' , 'Lost.Ticket.Review.Period.Elapsed', 'T05' , 'Charges.not.Authorized', '00','NonFraud CB', 'Unknown CB Reason') AS "CB Reason"
FROM order_attempt oa,
  order_attempt_item it,
  order_chargeback cb
WHERE oa.attempt_key = it.attempt_key
AND it.attempt_key   = cb.attempt_key
AND oa.platform      = 'regnow'
AND it.vendor_id    <> '1234'
AND oa.affiliate_id IS NOT NULL
AND oa.platform_order_date BETWEEN sysdate - 180 AND sysdate
AND TRUNC(cb.chargeback_date) BETWEEN
  &&date1 AND
  &&date2
ORDER BY ABS(oa.affiliate_id) DESC;
